#!/bin/sh

if ! grep -q "i3py" /home/pui/.xinitrc; then
    cp /home/pui/.xinitrc /home/pui/.xinitrc.b

    echo '/home/pui/pythonui/i3py &' > /tmp/.xinitrc
    cat /home/pui/.xinitrc >> /tmp/.xinitrc
    cp /tmp/.xinitrc /home/pui/.xinitrc
fi
